### ISSUE TITLE
Multiple messages, when chunked, may send out-of-order

### ISSUE THREAD

**Issue by edfletcher** [edfletcher/drc#26]
I think this might be in [irc-framework](https://github.com/kiwiirc/irc-framework) (because at least I can't recall writing this code explicitly) but either way, it's annoying as hell:

![Screenshot 2023-04-05 154850](https://user-images.githubusercontent.com/78338651/230228515-118f3d9b-9122-43f1-b3e1-4aff597f3d0e.jpg)

(in this, the sent order was 1-3-2)

**Comment by edfletcher** [comment]
Huzzah, figured it out! It _is_ in irc-framework and I've already got a [tested fix for it](https://github.com/edfletcher/irc-framework/commit/46214c6941d85158e288b9065da19dd5350d9754). Will write up an issue with all the details & a PR fixing it to their repo soon.

**Comment by edfletcher** [comment]
Closing, will now track this at https://github.com/kiwiirc/irc-framework/issues/361

**Comment by CovertDuck** [comment]
Good job, friend. :) ❤
