### ISSUE TITLE
Beef up README.md

### ISSUE THREAD

**Issue by CovertDuck** [edfletcher/drc#29]
We have some solid documentation, but I think it would be best to add some additional instructions to `README.md`.
Quickstart instructions, especially of the **Docker** variety, would encourage more people to spin up the project and contribute to it.

**Comment by edfletcher** [comment]
💯 percent agreed (if there was a "1000%" emoji I'd use that). Have been meaning to do this for awhile in fact, definitely need a better README as its the first thing most users will see, not the site.

**Comment by OlaPom** [comment]
Hi! Would you like some help with this issue? I'm interested in technical writing, and I'd like to get some practice. I've checked the documentation on your website, and based on it, I could help you with the file.

**Comment by CovertDuck** [comment]
@OlaPom: I'm all for it! I'm not sure when I myself would be able to make time for it but I can definitely put some time aside to go over your eventual Pull Request! :)

**Comment by CovertDuck** [comment]
@OlaPom: Please feel free to join us on **IRC** if you have questions or wish to discuss the project! We definitely could use the company! :D

**Server**
*irc.libera.chat*

**Channel**
*#discordrc*

BTW, that IRC server/channel should also be in the final **README.md**
